name: Arm Virtual Hardware
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  compile_examples:
    name: Compile Examples
    runs-on: ubuntu-22.04
    steps:
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: 3.25.2
      - name: Install GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 12.2.Rel1
      - name: Checkout CMSIS-DSP
        uses: actions/checkout@v3
        with:
          path: CMSIS-DSP
          fetch-depth: 0
      - name: Checkout CMSIS_5
        uses: actions/checkout@v3
        with:
          repository: ARM-Software/CMSIS_5
          ref: 5.9.0
          path: CMSIS_5
          fetch-depth: 0
      - name: Compile
        run: |
          cd CMSIS-DSP/AVH
          mkdir build
          cd build
          cmake \
            -DTARGET_CPU=cortex-m55 \
            -DCMSIS_PATH=../../CMSIS_5 \
            -DCMAKE_TOOLCHAIN_FILE=../toolchain/arm-none-eabi-gcc.cmake \
            ..
          make VERBOSE=1
      - name: Upload Compiled Examples
        uses: actions/upload-artifact@v3
        with:
          name: CMSIS-DSP-compiled-examples
          path: CMSIS-DSP/AVH/build/**/*.elf
