name: Arm Virtual Hardware
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test_examples:
    name: Test Examples
    runs-on: ubuntu-22.04
    strategy:
      matrix:
          cpu:
            - cortex-m0plus
            - cortex-m3
            - cortex-m4
            - cortex-m7
            - cortex-m33
            - cortex-m55
    concurrency:
      group: ${{ matrix.cpu }}
    env:
      AVH_API_TOKEN: ${{ secrets.AVH_API_TOKEN }}
      TARGET_CPU: ${{ matrix.cpu }}
    steps:
      - name: Checkout CMSIS-DSP
        uses: actions/checkout@v3
        with:
          path: CMSIS-DSP
          fetch-depth: 0
      - name: Checkout CMSIS_5
        uses: actions/checkout@v3
        with:
          repository: ARM-Software/CMSIS_5
          ref: 5.9.0
          path: CMSIS_5
          fetch-depth: 0
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: 3.25.2
      - name: Install GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 12.2.Rel1
      - name: Install Python dependencies
        run: |
          pip3 install -r CMSIS-DSP/AVH/requirements.txt
      - name: Compile Examples
        run: |
          cd CMSIS-DSP/AVH
          mkdir build
          cd build
          cmake \
            -DTARGET_CPU=${TARGET_CPU} \
            -DCMSIS_PATH=../../../CMSIS_5 \
            -DCMAKE_TOOLCHAIN_FILE=../toolchain/arm-none-eabi-gcc.cmake \
            ..
          make VERBOSE=1
      - name: Upload Compiled Examples
        uses: actions/upload-artifact@v3
        with:
          name: CMSIS-DSP-compiled-examples-${{ matrix.cpu }}
          path: CMSIS-DSP/AVH/build/**/*.elf
      - name: Test Examples on AVH
        run: |
          cd CMSIS-DSP/AVH
          python3 -u -m unittest examples_test.py
